spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      credentials:
        location: ${GCP_APPLICATION_CREDENTIALS:}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  servlet:
    context-path: /v1/api/chat
  port: ${PORT:8080 }

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_TIME}

springdoc:
  swagger-ui:
    enabled: true

services:
  chatting:
    apikey: ${CHATTING_API_KEY}

gcp:
  bucket:
    name: ${GCP_BUCKET_NAME}


